export { default as DealHeader } from './header/DealHeader' 
export { default as TitleBar } from './titleBar/TitleBar' 
export { default as ToolBar } from './toolBar/ToolBar' 
export { default as SampleSearchSection } from './sampleSearch/SampleSearchSection'
export { default as NearbyCities } from './nearbyCities/NearbyCities' 