export { default as About } from './about/About' 
export { default as Deal } from './details/Deal' 
export { default as Home } from './home/Home'  
export { default as Login } from './auth/Login'  
export { default as Register } from './auth/register/Register'  